---
- hosts: sclab
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: list nvidia GPU
      shell: fuser -v /dev/nvidia* 2>&1
      register: gpu_list

    - debug:
        msg: "{{ gpu_list.stdout_lines }}"
