---
- hosts: sclab
  remote_user: stevenokm
  #become: yes
  #become_user: root
  #become_method: sudo
  tasks:
    - name: list nvidia GPU
      shell: nvidia-smi --query-gpu=utilization.gpu,memory.used,memory.free,memory.total --format=csv,noheader
      register: gpu_util

    - name: list nvidia GPU
      shell: nvidia-smi --query-compute-apps=pid --format=csv,noheader | awk '{system("ps -o pid=,tty=,user=,start=,cmd= -p" $1)}' | awk '{system("who | grep " $2); print $0}'
      register: gpu_list

    - debug:
        msg:
        - "{{ gpu_util.stdout_lines }}"
        - "{{ gpu_list.stdout_lines }}"
