---
- hosts: sclab
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: download CUDA repo
      get_url:
      args:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
        dest: /tmp/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
        checksum: "md5:13ca2678965c6a013aab82d5628365de"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA repo
      apt:
      args:
        deb: /tmp/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: setup CUDA repo
      apt_key:
        url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: update apt
      apt: update_cache=yes

    - name: install CUDA 10.0
      apt:
        pkg: cuda-10-0
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 8.0
      apt:
        pkg: cuda-8-0
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 9.2
      apt:
        pkg: cuda-9-2
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 9.0
      apt:
        pkg: cuda-9-0
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: set default cuda device setting script
      copy:
        dest: "/etc/profile.d/cuda-default.sh"
        content: |
          export CUDA_VISIBLE_DEVICES="0"
          export CUDA_DEVICE_ORDER=PCI_BUS_ID

    - name: install environment modules
      apt:
        pkg: environment-modules
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

      #    - name: setup environment modules for cuda
      #      copy:
      #        src: "cuda"
      #        dest: "/usr/share/modules/modulefiles/"

