---
- hosts: sclab
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: download CUDA repo
      get_url:
      args:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.2.89-1_amd64.deb
        dest: /tmp/cuda-repo-ubuntu1604_10.2.89-1_amd64.deb
        checksum: "sha256:1e2091d7b67b1cbd001e28ebc07064f8c12bcc87ab0368c8beffca13500913bf"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA repo
      apt:
      args:
        deb: /tmp/cuda-repo-ubuntu1604_10.2.89-1_amd64.deb
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: setup CUDA repo
      apt_key:
        url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: update apt
      apt: update_cache=yes

    - name: unhold CUDA driver to upgrade
      shell:
        cmd: apt-mark unhold cuda-drivers nvidia-modprobe nvidia-settings

    - name: install CUDA driver
      apt:
        pkg:
        - cuda-drivers=440.118.02-1
        - nvidia-modprobe=440.118.02-0ubuntu1
        - nvidia-settings=440.118.02-0ubuntu1
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: hotfix nvidia-settings https://forums.developer.nvidia.com/t/109256
      get_url:
      args:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/nvidia-settings_440.118.02-0ubuntu1_amd64.deb
        dest: /tmp/nvidia-settings_440.118.02-0ubuntu1_amd64.deb
        checksum: "sha256:61a6b7e3d9884f1f5e025e7e0172ea024dbdc099dff7894181c900327a029eef"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install hotfix nvidia-settings
      apt:
      args:
        deb: /tmp/nvidia-settings_440.118.02-0ubuntu1_amd64.deb
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: prevent CUDA driver to upgrade
      shell:
        cmd: apt-mark hold cuda-drivers nvidia-modprobe nvidia-settings

    - name: install CUDA 10.1
      apt:
        pkg: cuda-10-1
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 10.0
      apt:
        pkg: cuda-10-0
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 8.0
      apt:
        pkg: cuda-8-0
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 9.0
      apt:
        pkg: cuda-9-0
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 9.2
      apt:
        pkg: cuda-9-2
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: install CUDA 10.2
      apt:
        pkg: cuda-10-2
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: set default cuda device setting script
      copy:
        dest: "/etc/profile.d/cuda-default.sh"
        content: |
          export CUDA_VISIBLE_DEVICES="0"
          export CUDA_DEVICE_ORDER=PCI_BUS_ID

    - name: install environment modules
      apt:
        pkg: environment-modules
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

    - name: setup environment modules for cuda
      copy:
        src: "cuda"
        dest: "/usr/share/modules/modulefiles/"

