---
- hosts: sclab
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: stop openvpn
      service:
        name: openvpn
        state: stopped
    - name: restart openvpn
      service:
        name: openvpn
        state: started
    - name: remount nfs
      shell: /bin/mount -a
