---
- hosts: sclab-upgrade
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: python3.6
      block:
        - name: ubuntu 16.04
          block:
          - name: import python3.6 repo
            apt_repository:
              repo: ppa:deadsnakes/ppa
          - name: install python3.6
            apt:
              pkg:
              - python3.6
              - python3.6-dev
              state: present
              update_cache: yes
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
        - name: ubuntu 18.04
          block:
          - name: install python3
            apt:
              pkg:
              - python3
              - python3-dev
              state: present
              update_cache: yes
          - name: install python3-pip
            apt:
              pkg: python3-pip
              state: present
              update_cache: yes
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "18.04"
        - name: install libpython3.6
          apt:
            pkg:
            - libpython3.6
            - libpython3.6-dev
            state: present
            update_cache: yes
        - name: install latest pip3.6
          shell: python3.6 -m pip install pip --upgrade --force
        - name: install pytorch 1.7.1
          pip:
            name: torch==1.7.1
            executable: pip3.6
            extra_args: -f https://download.pytorch.org/whl/cu102/torch_stable.html
        - name: install torchvision 0.8.2
          pip:
            name: torchvision==0.8.2
            executable: pip3.6
            extra_args: -f https://download.pytorch.org/whl/cu102/torch_stable.html
        - name: install tensorflow 2.3.2
          pip:
            name:
            - tensorflow==2.3.2
            - tensorflow-text==2.3.0
            executable: pip3.6
        - name: set python 3.6 jupyter notebook ip setting script
          copy:
            dest: "/etc/profile.d/jupyter36.sh"
            content: |
              alias jupyter-notebook3.6='echo -e "\nNOTE: change \033[1;33m{{ ansible_default_ipv4.address }}\033[0m to \033[1;33m{{ ansible_host }}\033[0m\n";python3.6 -m notebook --ip {{ ansible_default_ipv4.address }} --no-browser'
    - name: python3
      block:
      - name: python3.5
        block:
        - name: install python3
          apt:
            pkg:
            - python3
            - python3-dev
            state: present
            update_cache: yes
        - name: install libpython3.5
          apt:
            pkg:
            - libpython3.5
            - libpython3.5-dev
            state: present
            update_cache: yes
        - name: install python3-pip
          apt:
            pkg: python3-pip
            state: present
            update_cache: yes
        - name: upgrade latest pip3
          shell: python3 -m pip install pip --upgrade --force
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
      - name: glances part
        block:
        - name: install latest glances in python3
          pip:
            name: glances
            state: latest
            executable: pip3
        - name: install latest nvidia-ml-py3 in python3
          pip:
            name: nvidia-ml-py3
            state: latest
            executable: pip3
        - name: install latest py3nvml in python3
          pip:
            name: py3nvml
            state: latest
            executable: pip3
        - name: install llvm-8
          apt:
            pkg:
            - llvm-8
            - libllvm8
            state: present
            update_cache: yes
        - name: install latest llvmlite in python3
          pip:
            name: llvmlite
            state: latest
            executable: pip3
          environment:
            LLVM_CONFIG: llvm-config-8
        - name: install latest netifaces in python3
          pip:
            name: netifaces
            state: latest
            executable: pip3
        - name: install latest py-cpuinfo in python3
          pip:
            name: py-cpuinfo
            state: latest
            executable: pip3
        - name: install latest pySMART.smartx in python3
          pip:
            name: pySMART.smartx
            state: latest
            executable: pip3
        - name: install docker dependency for glances in python3
          pip:
            name: glances[docker]
            state: latest
            executable: pip3
        - name: install hddtemp
          apt:
            pkg: hddtemp
            state: present
            update_cache: yes
        - name: setup config file for glances
          copy:
            src: "glances.conf"
            dest: "/etc/glances/"
      - name: install latest kaggle in python3
        pip:
          name: kaggle
          executable: pip3
      - name: install 2.0.2 matplotlib in python3
        pip:
          name: matplotlib==2.0.2
          executable: pip3
      - name: install jupyter in python3
        pip:
          name: jupyter
          executable: pip3
          state: forcereinstall
      - name: set jupyter notebook ip setting script
        copy:
          dest: "/etc/profile.d/00-jupyter-alias.sh"
          content: |
            alias jupyter-notebook='echo -e "\nNOTE: change \033[1;33m{{ ansible_default_ipv4.address }}\033[0m to \033[1;33m{{ ansible_host }}\033[0m\n";jupyter-notebook --ip {{ ansible_default_ipv4.address }} --no-browser'
    - name: python2
      block:
      - name: install python
        apt:
          pkg:
          - python
          - python-dev
          state: present
          update_cache: yes
      - name: install libpython
        apt:
          pkg:
          - libpython2.7
          - libpython2.7-dev
          state: present
          update_cache: yes
      - name: install python-pip
        apt:
          pkg: python-pip
          state: present
          update_cache: yes
      - name: upgrade latest pip2
        shell: python -m pip install pip --upgrade --force
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
