---
- hosts: sclab
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  vars:
    fan_speed: 80
  tasks:
    - name: create setting script
      copy:
        dest: "/usr/share/lightdm/lightdm.conf.d/99-nvfanspeed.conf"
        content: |
          [Seat:*]
          #display-setup-script=/usr/bin/nvidia-settings {% for id in range(hostvars[inventory_hostname].gpus) %} -a [gpu:{{ id }}]/GPUFanControlState=1 -a [fan:{{ id }}]/GPUTargetFanSpeed={{ fan_speed }} {% endfor %}
          
          display-setup-script=/usr/bin/nvidia-settings {% for id in range(hostvars[inventory_hostname].gpus) %} -a [gpu:{{ id }}]/GPUFanControlState=0 {% endfor %}

    - name: restart xserver
      service:
        name: lightdm
        state: restarted

