---
- hosts: sclab
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: stop shutdown
      shell: /sbin/shutdown -c
      register: print_msg

    - debug: 
        msg: "{{ print_msg.stdout_lines }}"

