---
- hosts: sclab
  remote_user: stevenokm
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: install tree
      apt:
        pkg: tree
        state: present

    - name: install git-lfs
      block:
        - name: install git-lfs repo
          shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
        - name: install git-lfs
          apt:
            pkg: git-lfs
            state: present
